import { Product, Category, StockActivity } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'อุปกรณ์อิเล็กทรอนิกส์ (Electronics)',
    description: 'โทรศัพท์ มือถือ คอมพิวเตอร์ และอุปกรณ์เสริมต่างๆ',
    color: 'bg-blue-100 text-blue-800 border-blue-200',
  },
  {
    id: 'cat-2',
    name: 'เสื้อผ้าและแฟชั่น (Apparel)',
    description: 'เสื้อผ้า กระเป๋า รองเท้า เครื่องประดับ',
    color: 'bg-purple-100 text-purple-800 border-purple-200',
  },
  {
    id: 'cat-3',
    name: 'เครื่องใช้ในครัวเรือน (Household)',
    description: 'แก้วน้ำ อุปกรณ์ทำครัว ของตกแต่งบ้าน',
    color: 'bg-green-100 text-green-800 border-green-200',
  },
  {
    id: 'cat-4',
    name: 'อาหารและเครื่องดื่ม (Food & Drinks)',
    description: 'ชา กาแฟ ขนมขบเคี้ยว ของสด และอาหารแห้ง',
    color: 'bg-amber-100 text-amber-800 border-amber-200',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'สมาร์ทโฟน X1 Neo',
    sku: 'EL-SP-001',
    category: 'cat-1',
    price: 18900,
    costPrice: 14500,
    quantity: 12,
    minAlert: 5,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=300&auto=format&fit=crop&q=60',
    description: 'สมาร์ทโฟนกล้องโปร หน้าจอ AMOLED 120Hz ชิปเซ็ตประมวลผลเร็วแรงพิเศษ',
    sourceUrl: 'https://shopee.co.th/search?keyword=smartphone',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสินค้าหลัก A',
    expiryDate: '2027-12-31',
  },
  {
    id: 'prod-2',
    name: 'โน้ตบุ๊ก ProAir 14',
    sku: 'EL-LT-002',
    category: 'cat-1',
    price: 34900,
    costPrice: 28000,
    quantity: 3, // Low stock! minAlert is 5
    minAlert: 5,
    image: 'https://images.unsplash.com/photo-1496181130204-755241544e3f?w=300&auto=format&fit=crop&q=60',
    description: 'โน้ตบุ๊กบางเบาพกพาสะดวก แบตเตอรี่ใช้งานได้ยาวนาน 18 ชั่วโมง เหมาะสำหรับทำงาน',
    sourceUrl: 'https://www.lazada.co.th/tag/laptop/',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสินค้าหลัก A',
    expiryDate: '2028-06-15',
  },
  {
    id: 'prod-3',
    name: 'เสื้อยืด Cotton 100% (Oversized)',
    sku: 'AP-TS-003',
    category: 'cat-2',
    price: 490,
    costPrice: 200,
    quantity: 45,
    minAlert: 10,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=300&auto=format&fit=crop&q=60',
    description: 'เสื้อยืดเนื้อผ้าหนานุ่มพิเศษ ใส่สบาย ระบายอากาศได้ดี ดีไซน์ทันสมัย',
    sourceUrl: 'https://shopee.co.th/search?keyword=oversized%20t-shirt',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสำรอง B',
    expiryDate: '',
  },
  {
    id: 'prod-4',
    name: 'กระเป๋าเป้สะพายหลัง กันน้ำ',
    sku: 'AP-BP-004',
    category: 'cat-2',
    price: 1290,
    costPrice: 650,
    quantity: 0, // Out of stock!
    minAlert: 8,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&auto=format&fit=crop&q=60',
    description: 'กระเป๋าเป้เดินทาง พร้อมช่องใส่โน้ตบุ๊ก มีช่องชาร์จ USB ในตัว ทนทานต่อการขีดข่วน',
    sourceUrl: 'https://shopee.co.th/search?keyword=waterproof%20backpack',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสำรอง B',
    expiryDate: '',
  },
  {
    id: 'prod-5',
    name: 'แก้วเก็บอุณหภูมิสเตนเลส 24oz',
    sku: 'HH-TB-005',
    category: 'cat-3',
    price: 790,
    costPrice: 350,
    quantity: 28,
    minAlert: 6,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=60',
    description: 'เก็บความเย็นได้ยาวนาน 24 ชั่วโมง และความร้อน 12 ชั่วโมง ไม่มีหยดน้ำเกาะรอบแก้ว',
    sourceUrl: 'https://shopee.co.th/search?keyword=tumbler%2024oz',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสินค้าหน้าร้าน C',
    expiryDate: '2026-08-20',
  },
  {
    id: 'prod-6',
    name: 'น้ำผึ้งดอกไม้ป่าออร์แกนิก 500g',
    sku: 'FD-HN-006',
    category: 'cat-4',
    price: 350,
    costPrice: 180,
    quantity: 4, // Low stock! minAlert is 8
    minAlert: 8,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=300&auto=format&fit=crop&q=60',
    description: 'น้ำผึ้งแท้บริสุทธิ์จากธรรมชาติ ไม่แต่งสี ไม่แต่งกลิ่น เก็บเกี่ยวด้วยวิธีธรรมชาติ',
    sourceUrl: 'https://shopee.co.th/search?keyword=organic%20honey',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    warehouse: 'คลังสินค้าหน้าร้าน C',
    expiryDate: '2026-07-15',
  }
];

export const INITIAL_ACTIVITIES: StockActivity[] = [
  {
    id: 'act-1',
    productId: 'prod-1',
    productName: 'สมาร์ทโฟน X1 Neo',
    type: 'in',
    quantityChange: 15,
    oldQuantity: 0,
    newQuantity: 15,
    reason: 'นำเข้าสินค้าล็อตใหม่เข้าคลัง',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-2',
    productId: 'prod-1',
    productName: 'สมาร์ทโฟน X1 Neo',
    type: 'out',
    quantityChange: -3,
    oldQuantity: 15,
    newQuantity: 12,
    reason: 'ลูกค้าสั่งซื้อช่องทางหน้าร้าน',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    productId: 'prod-4',
    productName: 'กระเป๋าเป้สะพายหลัง กันน้ำ',
    type: 'out',
    quantityChange: -12,
    oldQuantity: 12,
    newQuantity: 0,
    reason: 'คำสั่งซื้อขายส่งจากตัวแทนจำหน่าย (สต็อกหมดชั่วคราว)',
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-4',
    productId: 'prod-6',
    productName: 'น้ำผึ้งดอกไม้ป่าออร์แกนิก 500g',
    type: 'adjust',
    quantityChange: -2,
    oldQuantity: 6,
    newQuantity: 4,
    reason: 'ปรับปรุงคลังสินค้า: ตรวจพบคราบชำรุดเสียหายระเบียงขนส่ง',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  }
];
